#!/bin/sh

set -e

# Initial setup
adduser reactive-sandbox -u 1000 -D

# Dependencies
apk add --no-cache bash openjdk8-jre-base supervisor

# Download & Extract
cassandra_url="https://archive.apache.org/dist/cassandra/3.9/apache-cassandra-3.9-bin.tar.gz"
elasticsearch_url="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.2.0-linux-x86_64.tar.gz"
kafka_url="http://mirrors.ibiblio.org/apache/kafka/2.3.0/kafka_2.11-2.3.0.tgz"
zookeeper_url="http://mirrors.ibiblio.org/apache/zookeeper/zookeeper-3.5.5/zookeeper-3.5.5.tar.gz"

mkdir -p /root/build
cd /root/build

wget -q "$cassandra_url" -O cassandra.tar.gz
wget -q "$elasticsearch_url" -O elasticsearch.tar.gz
wget -q "$kafka_url" -O kafka.tar.gz
wget -q "$zookeeper_url" -O zookeeper.tar.gz

mkdir -p /opt/cassandra
tar --strip-components 1 -x -C /opt/cassandra -f cassandra.tar.gz

mkdir -p /opt/elasticsearch
tar --strip-components 1 -x -C /opt/elasticsearch -f elasticsearch.tar.gz

mkdir -p /opt/kafka
tar --strip-components 1 -x -C /opt/kafka -f kafka.tar.gz

mkdir -p /opt/zookeeper
tar --strip-components 1 -x -C /opt/zookeeper -f zookeeper.tar.gz

# Directories & Permissions
chown -R reactive-sandbox /opt
mkdir -p /etc/supervisor.d/

# Clean up

cd /
rm -rf /root/build

